// @ts-nocheck
/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
import { createBlock as _createBlock, createCommentVNode as _createCommentVNode, createTextVNode as _createTextVNode, createVNode as _createVNode, openBlock as _openBlock, resolveComponent as _resolveComponent, toDisplayString as _toDisplayString, vModelText as _vModelText, withDirectives as _withDirectives } from 'vue'
// tslint:disable
/* eslint-disable */

export function indexTemplateHtml(_ctx, _cache) {
  const _component_file_uploader = _resolveComponent("file-uploader")

  return (_openBlock(), _createBlock("div", null, [
    _withDirectives(_createVNode("input", {
      type: "color",
      "onUpdate:modelValue": _cache[1] || (_cache[1] = $event => (_ctx.color = $event))
    }, null, 512 /* NEED_PATCH */), [
      [_vModelText, _ctx.color]
    ]),
    _createVNode("button", {
      onClick: _cache[2] || (_cache[2] = $event => (_ctx.compare()))
    }, "compare"),
    _createVNode("div", { class: "images" }, [
      _createVNode("div", { class: "left" }, [
        _createVNode(_component_file_uploader, {
          "onFile-uploaded": _cache[3] || (_cache[3] = $event => (_ctx.leftFileUploaded($event))),
          "onFile-got": _cache[4] || (_cache[4] = $event => (_ctx.leftFileGot($event))),
          accept: "image/*"
        }),
        _createVNode("div", { class: "header" }, [
          _createTextVNode(_toDisplayString(_ctx.leftFileName) + " " + _toDisplayString(_ctx.position) + " ", 1 /* TEXT */),
          (_ctx.leftPixelInfo)
            ? (_openBlock(), _createBlock("span", {
                key: 0,
                style: _ctx.leftStyle
              }, _toDisplayString(_ctx.leftPixelInfo), 5 /* TEXT, STYLE */))
            : _createCommentVNode("v-if", true)
        ]),
        _createVNode("canvas", {
          ref: "leftCanvas",
          onMousemove: _cache[5] || (_cache[5] = $event => (_ctx.onLeftMouseMove($event)))
        }, null, 544 /* HYDRATE_EVENTS, NEED_PATCH */)
      ]),
      _createVNode("div", { class: "right" }, [
        _createVNode(_component_file_uploader, {
          "onFile-uploaded": _cache[6] || (_cache[6] = $event => (_ctx.rightFileUploaded($event))),
          "onFile-got": _cache[7] || (_cache[7] = $event => (_ctx.rightFileGot($event))),
          accept: "image/*"
        }),
        _createVNode("div", { class: "header" }, [
          _createTextVNode(_toDisplayString(_ctx.rightFileName) + " " + _toDisplayString(_ctx.position) + " ", 1 /* TEXT */),
          (_ctx.rightPixelInfo)
            ? (_openBlock(), _createBlock("span", {
                key: 0,
                style: _ctx.rightStyle
              }, _toDisplayString(_ctx.rightPixelInfo), 5 /* TEXT, STYLE */))
            : _createCommentVNode("v-if", true)
        ]),
        _createVNode("canvas", {
          ref: "rightCanvas",
          onMousemove: _cache[8] || (_cache[8] = $event => (_ctx.onRightMouseMove($event)))
        }, null, 544 /* HYDRATE_EVENTS, NEED_PATCH */)
      ])
    ])
  ]))
}
/* eslint-enable */
// tslint:enable
