/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
/* eslint-disable */
import { App } from "./index"

// @ts-ignore
export function indexTemplateHtml(this: App) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',[_c('input',{directives:[{name:"model",rawName:"v-model",value:(_vm.color),expression:"color"}],attrs:{"type":"color"},domProps:{"value":(_vm.color)},on:{"input":function($event){if($event.target.composing){ return; }_vm.color=$event.target.value}}}),_vm._v(" "),_c('button',{on:{"click":function($event){return _vm.compare()}}},[_vm._v("compare")]),_vm._v(" "),_c('div',{staticClass:"images"},[_c('div',{staticClass:"left"},[_c('file-uploader',{attrs:{"accept":"image/*"},on:{"file-uploaded":function($event){return _vm.leftFileUploaded($event)},"file-got":function($event){return _vm.leftFileGot($event)}}}),_vm._v(" "),_c('div',[_vm._v(_vm._s(_vm.leftFileName)+" "+_vm._s(_vm.position)+" "+_vm._s(_vm.leftPixelInfo))]),_vm._v(" "),_c('canvas',{ref:"leftCanvas",on:{"mousemove":function($event){return _vm.onLeftMouseMove($event)}}})],1),_vm._v(" "),_c('div',{staticClass:"right"},[_c('file-uploader',{attrs:{"accept":"image/*"},on:{"file-uploaded":function($event){return _vm.rightFileUploaded($event)},"file-got":function($event){return _vm.rightFileGot($event)}}}),_vm._v(" "),_c('div',[_vm._v(_vm._s(_vm.rightFileName)+" "+_vm._s(_vm.position)+" "+_vm._s(_vm.rightPixelInfo))]),_vm._v(" "),_c('canvas',{ref:"rightCanvas",on:{"mousemove":function($event){return _vm.onRightMouseMove($event)}}})],1)])])}
// @ts-ignore
export var indexTemplateHtmlStatic = [  ]
/* eslint-enable */
// tslint:enable
